    language: php

    php:
      - '5.5'
      - '5.6'
      - '7.0'
      - 'hhvm'

    env:
      global:
        - 'DB_CONNECTION=mysql'
        - 'DB_HOST=localhost'
        - 'DB_DATABASE=codeuser'
        - 'DB_USERNAME=travis'

    before_install:
      - composer selfupdate

    install:
      - composer install

    before_script:
      - mysql -utravis -e "create database codeuser;"

    script:
      - vendor/bin/phpunit
